### PR TITLE
easier customization with defines in extra header file

### PR DESCRIPTION
**Pull request by TLINDEN**

### CODE REVIEW

**Comment by TLINDEN** [comment]
This would fix #4 too.

**Comment by nibrahim** [comment]
This makes sense. I'm on the road now and will integrate this once I'm back.

On 29 July 2017 14:01:29 GMT+05:30, "T.v.Dein" <notifications@github.com> wrote:
>This would fix #4 too.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nibrahim/showkeys/pull/5#issuecomment-318813800

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TLINDEN** [comment]
Oh, one more thing: `config.h` contains different defaults than you had in showkeys.c before. You may want to change them.

**Comment by nibrahim** [comment]
I'll check before merging. Thanks.

On 30 July 2017 20:04:01 GMT+05:30, "T.v.Dein" <notifications@github.com> wrote:
>Oh, one more thing: `config.h` contains different defaults than you had
>in showkeys.c before. You may want to change them.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/nibrahim/showkeys/pull/5#issuecomment-318905687

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nibrahim** [comment]
Merged. Thanks!

**Pull request closed without merging**
